=== newrelic/node-newrelic/documentation/otel-transformation-rules.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OpenTelemetry Transformation Rules",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["name", "type", "matcher"],
    "properties": {
      "name": { "type": "string" },
      "type": { "type": "string" },
      "matcher": {
        "type": "object",
        "required": ["required_span_kinds", "required_attribute_keys"],
        "properties": {
          "required_span_kinds": {
            "type": "array",
            "items": { "type": "string" }
          },
          "required_attribute_keys": {
            "type": "array",
            "items": { "type": "string" }
          },
          "attribute_conditions": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": { "type": "string" }
            }
          }
        },
        "additionalProperties": false
      },
      "attributes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "key": { "type": "string" },
            "value": { "type": ["string", "number", "boolean"] },
            "template": { "type": "string" },
            "regex": {
              "type": "object",
              "required": ["statement"],
              "properties": {
                "statement": { "type": "string" },
                "flags": { "type": "string" },
                "groups": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "group": { "type": ["integer", "string"] },
                      "key": { "type": "string" },
                      "name": { "type": "string" },
                      "regex": { 
                        "type": "object",
                        "properties": {
                          "statement": { "type": "string" },
                          "flags": { "type": "string" },
                          "name": { "type": "integer" },
                          "value": { "type": "integer" },
                          "prefix": {"type": "string" }
                        }
                      },
                      "value": { "type": ["integer", "string"] },
                      "prefix": { "type": "string" }
                    },
                    "additionalProperties": false
                  }
                }
              },
              "additionalProperties": false
            },
            "target": { "type": "string" },
            "name": { "type": "string" },
            "highSecurity": { "type": "boolean" },
            "mappings": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "key": { "type": "string" },
                  "arguments": { "type": "string" },
                  "body": { "type": "string" }
                },
                "required": ["key", "arguments", "body"],
                "additionalProperties": false
              }
            }
          },
          "additionalProperties": false
        }
      },
      "transaction": {
        "type": "object",
        "properties": {
          "type": { "type": "string" },
          "system": { "type": "string" },
          "name": {
            "type": "object",
            "properties": {
              "verb": { "type": "string" },
              "path": { "type": "string" },
              "prefix": { "type": "string" },
              "templatePath": { "type": "string" },
              "templateValue": { "type": "string" },
              "value": { "type": "string" }
            },
            "additionalProperties": false
          },
          "url": {
            "type": "object",
            "properties": {
              "template": { "type": "string" },
              "key": { "type": "string" },
              "mappings": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": { "type": "string" },
                    "arguments": { "type": "string" },
                    "body": { "type": "string" }
                  },
                  "required": ["key", "arguments", "body"],
                  "additionalProperties": false
                }
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      },
      "segment": {
        "type": "object",
        "properties": {
          "name": {
            "type": "object",
            "properties": {
              "template": { "type": "string" }
            },
            "additionalProperties": false
          },
          "host": { "type": ["string", "object"] },
          "system": { "type": "string" },
          "url": { "type": "string" },
          "operation": { "type": "string" },
          "type": { "type": "string" },
          "statement": { "type": "string" },
          "collection": { "type": "string" }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  }
}

=== newrelic/node-newrelic/lib/otel/traces/transformation-rules.json
[
  {
    "name": "OtelHttpServer1_23",
    "type": "server",
    "matcher": {
      "required_span_kinds": [
        "server"
      ],
      "required_attribute_keys": [
        "http.request.method"
      ]
    },
    "attributes": [
      {
        "key": "http.response.status_code",
        "target": "trace",
        "name": "http.statusCode"
      },
      {
        "key": "http.response.status_code",
        "target": "transaction",
        "name": "statusCode"
      },
      {
        "key": "http.request.method",
        "target": "trace",
        "name": "request.method"
      },
      {
        "key": "server.port",
        "target": "segment",
        "name": "port"
      },
      {
        "key": "http.route",
        "target": "segment",
        "name": "http.route"
      },
      {
        "key": "server.address",
        "target": "segment",
        "name": "host"
      }
    ],
    "transaction": {
      "type": "web",
      "name": {
        "verb": "http.request.method",
        "path": "http.route"
      },
      "url": {
        "template": "${url.scheme}://${server.address}${server.port}${url.path}${url.query}",
        "mappings": [
          {
            "key": "server.port",
            "arguments": "value",
            "body": "return value !== 80 && value !== 443 ? `:${value}` : ''"
          },
          {
            "key": "url.query",
            "arguments": "value",
            "body": "return value.startsWith('?') ? value : `?${value}`"
          }
        ]
      }
    }
  },
  {
    "name": "OtelHttpServer1_20",
    "type": "server",
    "matcher": {
      "required_span_kinds": [
        "server"
      ],
      "required_attribute_keys": [
        "http.method"
      ]
    },
    "attributes": [
      {
        "key": "http.status_code",
        "target": "trace",
        "name": "http.statusCode"
      },
      {
        "key": "http.status_code",
        "target": "transaction",
        "name": "statusCode"
      },
      {
        "key": "http.method",
        "target": "trace",
        "name": "request.method"
      },
      {
        "key": "net.host.port",
        "target": "segment",
        "name": "port"
      },
      {
        "key": "http.route",
        "target": "segment",
        "name": "http.route"
      },
      {
        "key": "net.host.name",
        "target": "segment",
        "name": "host"
      }
    ],
    "transaction": {
      "type": "web",
      "name": {
        "verb": "http.method",
        "path": "http.route"
      },
      "url": {
        "key": "http.url"
      }
    }
  },
  {
    "name": "OtelRpcServer1_20",
    "type": "server",
    "matcher": {
      "required_span_kinds": [
        "server"
      ],
      "required_attribute_keys": [
        "rpc.system"
      ]
    },
    "attributes": [
      {
        "key": "rpc.grpc.status_code",
        "target": "trace",
        "name": "response.status"
      },
      {
        "key": "rpc.grpc.status_code",
        "target": "segment",
        "name": "rpc.grpc.status_code"
      },
      {
        "key": "rpc.system",
        "target": "segment",
        "name": "component"
      },
      {
        "key": "rpc.method",
        "target": "trace",
        "name": "request.method"
      }
    ],
    "transaction": {
      "type": "web",
      "name": {
        "prefix": "rpc.system",
        "templatePath": "${rpc.service}/${rpc.method}"
      },
      "url": {
        "template": "${rpc.service}/${rpc.method}"
      }
    }
  },
  {
    "name": "FallbackServer",
    "type": "server",
    "matcher": {
      "required_span_kinds": [
        "server"
      ],
      "required_attribute_keys": []
    },
    "attributes": [],
    "transaction": {
      "type": "web",
      "name": {
        "value": "WebFrameworkUri//unknown"
      }
    }
  },
  {
    "name": "OtelMessagingConsumer1_30",
    "type": "consumer",
    "matcher": {
      "required_span_kinds": [
        "consumer"
      ],
      "required_attribute_keys": [
        "messaging.system",
        "messaging.operation.name",
        "messaging.destination.name"
      ]
    },
    "attributes": [
      {
        "key": "messaging.destination.name",
        "target": "trace",
        "name": "message.queueName",
        "highSecurity": true
      },
      {
        "key": "messaging.destination.name",
        "target": "segment",
        "name": "message.queueName",
        "highSecurity": true
      },
      {
        "key": "server.port",
        "target": "segment",
        "name": "port"
      },
      {
        "key": "server.address",
        "target": "segment",
        "name": "host"
      },
      {
        "key": "messaging.kafka.message.key",
        "target": "trace",
        "name": "message.routingKey",
        "highSecurity": true
      },
      {
        "key": "messaging.rabbitmq.destination.routing_key",
        "target": "trace",
        "name": "message.routingKey",
        "highSecurity": true
      }
    ],
    "transaction": {
      "type": "message",
      "system": "messaging.system",
      "name": {
        "templateValue": "${messaging.system}/${messaging.operation.name}/Named/${messaging.destination.name}"
      }
    }
  },
  {
    "name": "OtelMessagingConsumer1_24",
    "type": "consumer",
    "matcher": {
      "required_span_kinds": [
        "consumer"
      ],
      "required_attribute_keys": [
        "messaging.system",
        "messaging.operation",
        "messaging.destination.name"
      ]
    },
    "attributes": [
      {
        "key": "messaging.destination.name",
        "target": "trace",
        "name": "message.queueName",
        "highSecurity": true
      },
      {
        "key": "messaging.destination.name",
        "target": "segment",
        "name": "message.queueName",
        "highSecurity": true
      },
      {
        "key": "server.port",
        "target": "segment",
        "name": "port"
      },
      {
        "key": "server.address",
        "target": "segment",
        "name": "host"
      },
      {
        "key": "messaging.rabbitmq.destination.routing_key",
        "target": "trace",
        "name": "message.routingKey",
        "highSecurity": true
      }
    ],
    "transaction": {
      "type": "message",
      "system": "messaging.system",
      "name": {
        "templateValue": "${messaging.system}/${messaging.operation}/Named/${messaging.destination.name}"
      }
    }
  },
  {
    "name": "OtelMessagingConsumer1_17",
    "type": "consumer",
    "matcher": {
      "required_span_kinds": [
        "consumer"
      ],
      "required_attribute_keys": [
        "messaging.destination_kind"
      ]
    },
    "attributes": [
      {
        "key": "messaging.destination",
        "target": "trace",
        "name": "message.queueName",
        "highSecurity": true
      },
      {
        "key": "messaging.destination",
        "target": "segment",
        "name": "message.queueName",
        "highSecurity": true
      },
      {
        "key": "net.peer.port",
        "target": "segment",
        "name": "port"
      },
      {
        "key": "net.peer.name",
        "target": "segment",
        "name": "host"
      },
      {
        "key": "messaging.rabbitmq.routing_key",
        "target": "trace",
        "name": "message.routingKey",
        "highSecurity": true
      }
    ],
    "transaction": {
      "type": "message",
      "system": "messaging.system",
      "name": {
        "templateValue": "${messaging.system}/${messaging.destination_kind}/Named/${messaging.destination}"
      }
    }
  },
  {
    "name": "FallbackConsumer",
    "type": "consumer",
    "matcher": {
      "required_span_kinds": [
        "consumer"
      ],
      "required_attribute_keys": []
    },
    "attributes": [],
    "transaction": {
      "type": "message",
      "system": "messaging.system",
      "name": {
        "value": "unknown"
      }
    }
  },
  {
    "name": "OtelDbClientRedis1_24",
    "type": "db",
    "matcher": {
      "required_span_kinds": [
        "client"
      ],
      "required_attribute_keys": [
        "db.system.name",
        "server.address",
        "server.port"
      ],
      "attribute_conditions": {
        "db.system.name": ["redis", "memcached"]
      }
    },
    "attributes": [
      {
        "key": "db.system.name",
        "target": "segment",
        "name": "product"
      },
      {
        "key": "server.address",
        "target": "segment",
        "name": "host"
      },
      {
        "key": "server.port",
        "target": "segment",
        "name": "port_path_or_id"
      }
    ],
    "segment": {
      "operation": "db.statement",
      "type": "db.system.name",
      "name": {
        "template": "Datastore/operation/${type}/${operation}"
      } 
    }
  },
  {
    "name": "OtelDbClientMongo1_24",
    "type": "db",
    "matcher": {
      "required_span_kinds": [
        "client"
      ],
      "required_attribute_keys": [
        "db.system.name",
        "server.address",
        "server.port"
      ],
      "attribute_conditions": {
        "db.system.name": ["mongodb"]
      }
    },
    "attributes": [
      {
        "key": "db.system.name",
        "target": "segment",
        "name": "product"
      },
      {
        "key": "db.namespace",
        "target": "segment",
        "name": "database_name"
      },
      {
        "key": "server.address",
        "target": "segment",
        "name": "host"
      },
      {
        "key": "server.port",
        "target": "segment",
        "name": "port_path_or_id"
      }
    ],
    "segment": {
      "operation": "db.operation",
      "collection": "db.mongodb.collection",
      "type": "db.system.name",
      "name": {
        "template": "Datastore/statement/${type}/${collection}/${operation}"
      } 
    }
  },
  {
    "name": "OtelDbClient1_24",
    "type": "db",
    "matcher": {
      "required_span_kinds": [
        "client"
      ],
